AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  E-Commerce Serverless Backend
  SAM Template for 3-developer hackathon project

# Global configuration for all Lambda functions
Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable
        ORDERS_TABLE: !Ref OrdersTable
        ORDER_QUEUE_URL: !Ref OrderProcessingQueue
        ORDER_TOPIC_ARN: !Ref OrderCompletedTopic
        PRODUCT_IMAGES_BUCKET: !Ref ProductImagesBucket

# No parameters needed - using single dev environment

Resources:
  ###############################################################################
  # DEVELOPER 1: BACKEND CORE & ORCHESTRATION
  ###############################################################################

  # DynamoDB Table for Products
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dev-ProductsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Developer
          Value: Dev1
        - Key: Environment
          Value: dev

  # DynamoDB Table for Orders
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dev-OrdersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserOrdersIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Developer
          Value: Dev1
        - Key: Environment
          Value: dev

  # SQS Queue for Order Processing
  OrderProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dev-OrderProcessingQueue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrderProcessingDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Developer
          Value: Dev1
        - Key: Environment
          Value: dev

  # Dead Letter Queue for failed order processing
  OrderProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dev-OrderProcessingDLQ
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Developer
          Value: Dev1
        - Key: Environment
          Value: dev

  # SNS Topic for Order Completion Notifications
  OrderCompletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: dev-OrderCompletedTopic
      DisplayName: Order Completed Notifications
      Tags:
        - Key: Developer
          Value: Dev1
        - Key: Environment
          Value: dev

  # Step Functions State Machine for Order Processing Workflow
  OrderProcessingWorkflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: dev-OrderProcessingWorkflow
      DefinitionUri: dev1-backend-core/state-machines/order-workflow.asl.json
      DefinitionSubstitutions:
        OrdersTableName: !Ref OrdersTable
        OrderTopicArn: !Ref OrderCompletedTopic
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Tags:
        Developer: Dev1
        Environment: dev

  # IAM Role for Step Functions
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt OrdersTable.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref OrderCompletedTopic
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt OrderProcessingQueue.Arn

  ###############################################################################
  # DEVELOPER 2: API & AUTHENTICATION
  ###############################################################################

  # Cognito User Pool for User Management
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: dev-ECommerceUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      UserPoolTags:
        Developer: Dev2
        Environment: dev

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: dev-ECommerceClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  # API Gateway REST API
  ECommerceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: dev-ECommerceAPI
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
      Tags:
        Developer: Dev2
        Environment: dev

  # Lambda Function: Auth Handler (Login, Register, etc.)
  AuthHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-AuthHandler
      Handler: app.lambda_handler
      CodeUri: dev2-api-auth/lambdas/auth_handler/
      Description: Handles user authentication operations
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          USER_POOL_CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
                - cognito-idp:AdminGetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        AuthPost:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /auth
            Method: POST
            Auth:
              Authorizer: NONE
      Tags:
        Developer: Dev2
        Environment: dev

  # Lambda Function: Order Entry Handler
  OrderEntryHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-OrderEntryHandler
      Handler: app.lambda_handler
      CodeUri: dev2-api-auth/lambdas/order_entry_handler/
      Description: Accepts new orders and queues them for processing
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt OrderProcessingQueue.Arn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt ProductsTable.Arn
      Events:
        CreateOrder:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /orders
            Method: POST
      Tags:
        Developer: Dev2
        Environment: dev

  ###############################################################################
  # DEVELOPER 3: DATA & MEDIA MANAGEMENT
  ###############################################################################

  # S3 Bucket for Product Images
  ProductImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub dev-ecommerce-product-images-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Developer
          Value: Dev3
        - Key: Environment
          Value: dev

  # S3 Bucket Policy (if needed for public read access to specific paths)
  ProductImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ProductImagesBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  # Lambda Function: Get Products Handler
  GetProductsHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-GetProductsHandler
      Handler: app.lambda_handler
      CodeUri: dev3-data-media/lambdas/get_products_handler/
      Description: Retrieves product list from DynamoDB
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:GetItem
              Resource:
                - !GetAtt ProductsTable.Arn
                - !Sub ${ProductsTable.Arn}/index/*
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /products
            Method: GET
            Auth:
              Authorizer: NONE  # Public endpoint
      Tags:
        Developer: Dev3
        Environment: dev

  # Lambda Function: Upload URL Handler (Pre-signed URLs)
  UploadUrlHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-UploadUrlHandler
      Handler: app.lambda_handler
      CodeUri: dev3-data-media/lambdas/upload_url_handler/
      Description: Generates S3 pre-signed URLs for product image uploads
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub ${ProductImagesBucket.Arn}/*
      Events:
        GetUploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /products/upload
            Method: GET
      Tags:
        Developer: Dev3
        Environment: dev

###############################################################################
# OUTPUTS
###############################################################################

Outputs:
  # API Gateway
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ECommerceApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
    Export:
      Name: dev-ApiUrl

  # Cognito
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: dev-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: dev-UserPoolClientId

  # DynamoDB Tables
  ProductsTableName:
    Description: Products DynamoDB Table Name
    Value: !Ref ProductsTable
    Export:
      Name: dev-ProductsTableName

  OrdersTableName:
    Description: Orders DynamoDB Table Name
    Value: !Ref OrdersTable
    Export:
      Name: dev-OrdersTableName

  # SQS & SNS
  OrderQueueUrl:
    Description: Order Processing Queue URL
    Value: !Ref OrderProcessingQueue
    Export:
      Name: dev-OrderQueueUrl

  OrderTopicArn:
    Description: Order Completed Topic ARN
    Value: !Ref OrderCompletedTopic
    Export:
      Name: dev-OrderTopicArn

  # S3
  ProductImagesBucketName:
    Description: Product Images S3 Bucket Name
    Value: !Ref ProductImagesBucket
    Export:
      Name: dev-ProductImagesBucketName

  # Step Functions
  OrderWorkflowArn:
    Description: Order Processing Workflow State Machine ARN
    Value: !Ref OrderProcessingWorkflow
    Export:
      Name: dev-OrderWorkflowArn
